name: "- Deploy Windows VM Import"
run-name: "Windows VM Import - ${{ inputs.environment }} VM: ${{ inputs.vmName }}"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: Environment
        options:
        - DEV
        - UAT
        - QA
        - PROD
      location:
        type: choice
        required: true
        description: Deployment Location
        options:
        - eastus2
        - uksouth
        - centralus
        - ukwest
      vmName:
        type: string
        required: true
        description: Name of the VM to import
      resourceGroupName:
        type: string
        required: true
        description: Resource group containing the VM
      vmSize:
        type: string
        required: false
        description: Size of the VM (e.g. Standard_D2s_v3)
        default: "Standard_D2s_v3"
      nicNames:
        type: string
        required: false
        description: "Name of the NIC (leave blank to use default naming)"
        default: ""
      osDiskName:
        type: string
        required: false
        description: Name of the OS disk
        default: ""
      dataDiskCount:
        type: string
        required: false
        description: Number of data disks (default 0)
        default: "0"
      dataDiskNames:
        type: string
        required: false
        description: JSON array of data disk names (e.g. '["disk1","disk2"]')
        default: ""
      generateOnly:
        type: boolean
        required: false
        description: Generate import commands without executing them
        default: false

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    outputs:
      nic_names_json: ${{ steps.validate.outputs.nic_names_json }}
      nic_count: ${{ steps.validate.outputs.nic_count }}
    steps:
    - name: Validate inputs
      id: validate
      run: |
        if [[ -z "${{ inputs.vmName }}" ]]; then
          echo "::error::VM Name is required"
          exit 1
        fi

        if [[ -z "${{ inputs.resourceGroupName }}" ]]; then
          echo "::error::Resource Group Name is required"
          exit 1
        fi

        if [[ "${{ inputs.dataDiskCount }}" -lt 0 ]]; then
          echo "::error::Data Disk Count must be 0 or greater"
          exit 1
        fi

        # Process and validate NIC names
        if [[ ! -z "${{ inputs.nicNames }}" ]]; then
          # Convert direct input to a JSON array for later processing
          processed_nic_names="[\"${{ inputs.nicNames }}\"]"
          echo "nic_names_json=$processed_nic_names" >> $GITHUB_OUTPUT
          echo "nic_count=1" >> $GITHUB_OUTPUT
          echo "Using NIC name: ${{ inputs.nicNames }}"
        else
          # Default to single NIC with auto-naming
          echo "nic_count=1" >> $GITHUB_OUTPUT
          echo "Using default naming for the NIC"
        fi

        # Validate data disk names JSON if provided
        if [[ ! -z "${{ inputs.dataDiskNames }}" ]]; then
          if ! echo "${{ inputs.dataDiskNames }}" | jq empty; then
            echo "::error::Data disk names must be a valid JSON array"
            exit 1
          fi
          
          disk_count=$(echo "${{ inputs.dataDiskNames }}" | jq length)
          if [[ $disk_count -ne ${{ inputs.dataDiskCount }} ]]; then
            echo "::error::Number of data disk names ($disk_count) does not match data disk count (${{ inputs.dataDiskCount }})"
            exit 1
          fi
        fi

        echo "All validations passed!"

  windows_vm_import:
    needs: validate-inputs
    name: "VM Import Operation"
    uses: ./.github/workflows/WindowsVMImport.yml
    secrets:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      BACKEND_STORAGE_ACCOUNT: ${{ secrets.BACKEND_STORAGE_ACCOUNT }}
      BACKEND_RESOURCE_GROUP: ${{ secrets.BACKEND_RESOURCE_GROUP }}
    with:
      environment: ${{ inputs.environment }}
      location: ${{ inputs.location }}
      vmName: ${{ inputs.vmName }}
      resourceGroupName: ${{ inputs.resourceGroupName }}
      vmSize: ${{ inputs.vmSize }}
      nicCount: ${{ needs.validate-inputs.outputs.nic_count }}
      nicNames: ${{ needs.validate-inputs.outputs.nic_names_json || inputs.nicNames }}
      osDiskName: ${{ inputs.osDiskName }}
      dataDiskCount: ${{ inputs.dataDiskCount }}
      dataDiskNames: ${{ inputs.dataDiskNames }}
      generateOnly: ${{ inputs.generateOnly }}
