name: 'Deploy MSSQL Database'
run-name: '${{github.actor}} - Deployingto_${{inputs.subscription}}_${{inputs.environment}}'
on:
  workflow_dispatch:
    inputs:
      requestType:
        type: choice
        required: true
        description: Request Type
        options:
          - Create
          - Remove
        default: "Create"
      subscription:
        type: string
        required: true
        description: Please enter your subscription Name
      location:
        type: choice
        description: Pick the Location
        options:
          - eastus2
          - centralus
      environment:
        type: choice
        description: Choose the environment
        options:
          - dev
          - qa
          - UAT
          - Prod
      purpose:
        type: string
        description: purpose/sequence
        required: true
      db_names:
        type: string
        required: true
        description: Database names list (comma-separated) ["db1","db2"]
      skuname:
        type: choice
        description: Database SKU
        options:
            - S0
            - P2
            - Basic
            - ElasticPool
            - BC_Gen5_2
            - HS_Gen4_1
            - GP_S_Gen5_2
            - DW100c
            - DS100
      purposeRG:
        type: string
        required: true
        description: Resource Group Purpose
      zoneredundancy:
        type: choice
        options:
            - "false"
            - "true"
      dbcollation:
        type: string
        required: false
        description: Specify Collation of the database
        default: SQL_Latin1_General_CP1_CI_AS

jobs:
  sql-database_create:
    if: (github.event.inputs.requestType == 'Create')
    name: 'Deploying - MSSQL Database'
    uses: ./.github/workflows/Createmssqldatabase.yml
    secrets:
          ARM_CLIENT_ID:            ${{secrets.AZURE_CLIENT_ID}}
          ARM_CLIENT_SECRET:        ${{secrets.AZURE_CLIENT_SECRET}}
          ARM_SUBSCRIPTION_ID:      ${{secrets.AZURE_SUBSCRIPTION_ID}}
          ARM_TENANT_ID:            ${{secrets.AZURE_TENANT_ID}}
          BACKEND_STORAGE_ACCOUNT:  ${{secrets.BACKEND_STORAGE_ACCOUNT}}
          BACKEND_RESOURCE_GROUP:   ${{secrets.BACKEND_RESOURCE_GROUP}}
    with:
      name: 'mssql-db'
      subscription: '${{inputs.subscription}}'
      location: '${{inputs.location}}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purpose}}'
      db_names: '${{inputs.db_names}}'
      skuname: '${{inputs.skuname}}'
      purposeRG: '${{inputs.purposeRG}}'
      zoneredundancy: '${{inputs.zoneredundancy}}'
      dbcollation: '${{inputs.dbcollation}}'

  sql-database_remove:
    if: (github.event.inputs.requestType == 'Remove')
    name: 'Removing - MSSQL Database'
    uses: ./.github/workflows/Createmssqldatabase.yml
    secrets:
          ARM_CLIENT_ID:            ${{secrets.AZURE_CLIENT_ID}}
          ARM_CLIENT_SECRET:        ${{secrets.AZURE_CLIENT_SECRET}}
          ARM_SUBSCRIPTION_ID:      ${{secrets.AZURE_SUBSCRIPTION_ID}}
          ARM_TENANT_ID:            ${{secrets.AZURE_TENANT_ID}}
          BACKEND_STORAGE_ACCOUNT:  ${{secrets.BACKEND_STORAGE_ACCOUNT}}
          BACKEND_RESOURCE_GROUP:   ${{secrets.BACKEND_RESOURCE_GROUP}}
    with:
      name: 'mssql-db'
      subscription: '${{inputs.subscription}}'
      location: '${{inputs.location}}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purpose}}'
      db_names: '${{inputs.db_names}}'
      skuname: '${{inputs.skuname}}'
      purposeRG: '${{inputs.purposeRG}}'
      zoneredundancy: '${{inputs.zoneredundancy}}'
      dbcollation: '${{inputs.dbcollation}}'