name: 'Deploy MSSQL Server'
run-name: '${{github.actor}} - Deployingto_${{inputs.subscription}}_${{inputs.environment}}'
on:
    workflow_dispatch:
     inputs:
        requesttype:
          type: choice
          required: true
          description: Request Type
          options:
              - Create (with New RG)
              - Create (with Existing RG)
              - Remove 
          default:
              "Create (with New RG)"
        subscription:
          type: string
          required: true
          description: Please enter your subcription Name
        location:
          type: choice
          description: Pick the Location
          options:
            - eastus2
            - centralus
        secondary_location:
          type: choice
          description: Pick the Location for secondary
          options:
            - eastus2
            - centralus
          default:
              "centralus"
        environment:
          type: choice
          description: choose the environment
          options:
             - dev
             - qa 
             - UAT
             - Prod
        purposeRG:
          type: string
          required: true
          description: Resource Group Purpose.......... Hyphen designate an existing RG
        purpose:
          type: string
          description: purpose/sequence
          required: true
        subnetname:
          type: string
          required: true
          description: Enter the subnet name for db end points
        dbserverversion:
          type: string
          required: false
          default: "12.0"
          description: SQL Server version
        tlsversion:
          type: string
          required: false
          default: "1.2"
          description: Minimum TLS version
jobs:
  Deploying-Resource-Group:
    if: (github.event.inputs.requestType == 'Create (with New RG)')
    name: 'Deploying - resource-group'
    uses: ./.github/workflows/CreateResourceGroup.yml
    secrets:
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    with:
      name: 'resource-group'
      subscription: '${{inputs.subscription}}'
      location: '${{inputs.location}}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purposeRG}}'
  mysql-server_new_rg:
    if: (github.event.inputs.requestType == 'Create (with New RG)')
    name: 'Deploying - MSSQL server'
    uses: ./.github/workflows/Createmssqlserver.yml
    needs: Deploying-Resource-Group
    secrets: 
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    with:
      name: 'mssql'
      subscription: '${{inputs.subscription}}'
      location: '${{inputs.location}}'
      secondary_location: '${{inputs.secondary_location}}'
      purposeRG: '${{inputs.purposeRG}}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purpose}}'
      subnetname: '${{inputs.subnetname}}'
      dbserverversion: '${{inputs.dbserverversion}}'
      tlsversion: '${{inputs.tlsversion}}'
  mysql-server_existing_rg:
    if: (github.event.inputs.requestType == 'Create (with Existing RG)')
    name: 'Deploying - MSSQL server'
    uses: ./.github/workflows/Createmssqlserver.yml
    secrets: 
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    with:
      name: 'mssql'
      subscription: '${{inputs.subscription}}'
      purposeRG: '${{inputs.purposeRG}}'
      location: '${{inputs.location}}'
      secondary_location: '${{inputs.secondary_location}}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purpose}}'
      subnetname: '${{inputs.subnetname}}'
      dbserverversion: '${{inputs.dbserverversion}}'
      tlsversion: '${{inputs.tlsversion}}'
  mysql-server_remove:
    if: (github.event.inputs.requestType == 'Remove')
    name: 'Removing - MSSQL server'
    uses: ./.github/workflows/Createmssqlserver.yml
    secrets: 
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    with:
      name: 'mssql'
      subscription: '${{inputs.subscription}}'
      location: '${{inputs.location}}'
      secondary_location: '${{inputs.secondary_location}}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purpose}}'
      purposeRG: '${{inputs.purposeRG}}'
      subnetname: '${{inputs.subnetname}}'
      dbserverversion: '${{inputs.dbserverversion}}'
      tlsversion: '${{inputs.tlsversion}}'