name: 'zWindows VM Maintain (Call)'
run-name: '${{github.actor}} - Maintain Windows VM'
on:
  workflow_call:
    inputs:
      requestType:
        type: string
        required: true
      environment:
        type: string
        required: true
      location:
        type: string
        required: false
      vmsize:
        type: string
        required: false
      purpose:
        type: string
        required: false
      purposeRG:
        type: string
        required: false
      diskSizeGB:
        type: string
        required: false
      diskStorageAccountType:
        type: string
        required: false
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true

permissions:
  contents: read

jobs:
  wvm-maintain:
    name: 'Maintain Windows VM'
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ROOT_PATH: 'Azure/windows-vm/update'
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    
    - name: Az login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
        enable-AzPSSession: true

    - name: 'Terraform Initialize'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: latest
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: ${{env.ROOT_PATH}}
        tf_actions_comment: true
      env:
        TF_VAR_request_type: '${{inputs.requestType}}'
        TF_VAR_location: '${{inputs.location}}'
        TF_VAR_vm_size: '${{inputs.vmsize}}'
        TF_VAR_purpose: '${{inputs.purpose}}'
        TF_VAR_purpose_rg: '${{inputs.purposeRG}}'
        TF_VAR_disk_size_gb: '${{inputs.diskSizeGB}}'
        TF_VAR_disk_storage_account_type: '${{inputs.diskStorageAccountType}}'

    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: latest
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: ${{env.ROOT_PATH}}
        tf_actions_comment: true
        tf_actions_cli_options: >-
          ${{ inputs.requestType == 'Update VM SKU' && '-target="azapi_update_resource.vm_vmSize"' ||
              inputs.requestType == 'Update (Data Disk)' && '-target="azapi_update_resource.dd_*"' ||
              inputs.requestType == 'Update (OS Disk)' && '-target="azapi_update_resource.vm_os_storage_account_type"' ||
              inputs.requestType == 'Start VM' && '-target="azapi_resource_action.vm_start"' ||
              inputs.requestType == 'Stop VM' && '-target="azapi_resource_action.vm_stop"' ||
              inputs.requestType == 'Restart VM' && '-target="azapi_resource_action.vm_restart"' || '' }}
      env:
        TF_VAR_request_type: '${{inputs.requestType}}'
        TF_VAR_location: '${{inputs.location}}'
        TF_VAR_vm_size: '${{inputs.vmsize}}'
        TF_VAR_purpose: '${{inputs.purpose}}'
        TF_VAR_purpose_rg: '${{inputs.purposeRG}}'
        TF_VAR_disk_size_gb: '${{inputs.diskSizeGB}}'
        TF_VAR_disk_storage_account_type: '${{inputs.diskStorageAccountType}}'

    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: latest
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: ${{env.ROOT_PATH}}
        tf_actions_comment: true
        tf_actions_cli_options: >-
          ${{ inputs.requestType == 'Update VM SKU' && '-target="azapi_update_resource.vm_vmSize"' ||
              inputs.requestType == 'Update (Data Disk)' && '-target="azapi_update_resource.dd_*"' ||
              inputs.requestType == 'Update (OS Disk)' && '-target="azapi_update_resource.vm_os_storage_account_type"' ||
              inputs.requestType == 'Start VM' && '-target="azapi_resource_action.vm_start"' ||
              inputs.requestType == 'Stop VM' && '-target="azapi_resource_action.vm_stop"' ||
              inputs.requestType == 'Restart VM' && '-target="azapi_resource_action.vm_restart"' || '' }}
      env:
        TF_VAR_request_type: '${{inputs.requestType}}'
        TF_VAR_location: '${{inputs.location}}'
        TF_VAR_vm_size: '${{inputs.vmsize}}'
        TF_VAR_purpose: '${{inputs.purpose}}'
        TF_VAR_purpose_rg: '${{inputs.purposeRG}}'
        TF_VAR_disk_size_gb: '${{inputs.diskSizeGB}}'
        TF_VAR_disk_storage_account_type: '${{inputs.diskStorageAccountType}}' 